### ISSUE TITLE
[Windows] Packaging cannot delete temporary build file 

### ISSUE THREAD

**Issue by lvcabral** [ViacomInc/roku_builder#22]
When packaging apparently the Faraday UploadIO object is not closing the zip file, causing File.delete() to fail during the sideload. Check the debug stack trace below. 

If I comment the delete line (loader.rb:49) the package works but the zip file is not deleted.

```
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/roku_builder-4.2.0/lib/roku_builder/plugins/loader.rb:49:in `delete': Permission denied @ unlink_internal - C:/Users/Marcelo/Dropbox/Projects/Roku/ro
kanban-trello/out/2393.zip (Errno::EACCES)
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/roku_builder-4.2.0/lib/roku_builder/plugins/loader.rb:49:in `sideload'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/roku_builder-4.2.0/lib/roku_builder/plugins/packager.rb:40:in `package'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/roku_builder-4.2.0/lib/roku_builder.rb:159:in `block in execute_command'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/roku_builder-4.2.0/lib/roku_builder.rb:151:in `each'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/roku_builder-4.2.0/lib/roku_builder.rb:151:in `execute_command'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/roku_builder-4.2.0/lib/roku_builder.rb:69:in `execute'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/roku_builder-4.2.0/lib/roku_builder.rb:45:in `run'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/roku_builder-4.2.0/bin/roku:9:in `<top (required)>'
        from C:/Ruby24-x64/bin/roku:22:in `load'
        from C:/Ruby24-x64/bin/roku:22:in `<main>'
```

**Comment by lvcabral** [comment]
I'm not sure how to fix this, will investigate it later.
